### ISSUE TITLE
In Call Issue Fix

### ISSUE THREAD

**Issue by samsung-miui-i9060** [SamsungBCM-GrandNeo/android_vendor_samsung_baffinlite#1]
Kindly Fix the issue of incall in the following rom. Kindly help me in creating the MIUI rom for samsung i9060 i have the device. 
http://forum.xda-developers.com/android/software/guide-build-port-miui-rom-to-device-t3250984

**Comment by luk1337** [comment]
I'm no longer working on this device. I'd do if someone has bought me one.

**Comment by samsung-miui-i9060** [comment]
I have the device. Can u teach me to fix the bug.

**Comment by luk1337** [comment]
Do a barrel roll and some other tricks. That should do it.

**Comment by samsung-miui-i9060** [comment]
what do you mean by that.. barrel Roll..
